#!/usr/bin/env node
/**
 * Shopify App Intel — Newsletter Generator
 * Generates a markdown newsletter from a diff file
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

function loadDiff(path) {
  return JSON.parse(readFileSync(path, 'utf-8'));
}

function generateNewsletter(diff) {
  const date = new Date().toISOString().split('T')[0];
  const lines = [];

  lines.push(`# 📊 Shopify App Intel — ${date}`);
  lines.push('');
  lines.push(`> Comparing snapshots from ${diff.oldSnapshot.split('T')[0]} to ${diff.newSnapshot.split('T')[0]}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| 🆕 New Apps | ${diff.summary.newApps} |`);
  lines.push(`| ❌ Removed Apps | ${diff.summary.removedApps} |`);
  lines.push(`| 🔄 Apps with Changes | ${diff.summary.appsWithChanges} |`);
  lines.push('');

  // New Apps
  if (diff.added.length > 0) {
    lines.push('## 🆕 New Apps');
    lines.push('');
    for (const app of diff.added) {
      lines.push(`### ${app.name}`);
      lines.push('');
      lines.push(`- **Handle:** \`${app.handle}\``);
      if (app.rating) lines.push(`- **Rating:** ${app.rating} ⭐ (${app.reviewCount} reviews)`);
      lines.push(`- **Pricing:** ${app.pricing}`);
      if (app.description) lines.push(`- **Description:** ${app.description}`);
      if (app.categories) lines.push(`- **Categories:** ${app.categories.join(', ')}`);
      lines.push('');
    }
  }

  // Removed Apps
  if (diff.removed.length > 0) {
    lines.push('## ❌ Removed Apps');
    lines.push('');
    for (const app of diff.removed) {
      lines.push(`- **${app.name}** (\`${app.handle}\`) — was ${app.rating}⭐ with ${app.reviewCount} reviews`);
    }
    lines.push('');
  }

  // Changes
  if (diff.changes.length > 0) {
    lines.push('## 🔄 Notable Changes');
    lines.push('');

    // Group by change type
    const pricingChanges = diff.changes.filter(c => c.changes.some(ch => ch.type === 'pricing'));
    const ratingChanges = diff.changes.filter(c => c.changes.some(ch => ch.type === 'rating'));
    const reviewChanges = diff.changes.filter(c => c.changes.some(ch => ch.type === 'reviewCount'));

    if (pricingChanges.length > 0) {
      lines.push('### 💰 Pricing Changes');
      lines.push('');
      lines.push('| App | Old Price | New Price |');
      lines.push('|-----|-----------|-----------|');
      for (const app of pricingChanges) {
        const ch = app.changes.find(c => c.type === 'pricing');
        lines.push(`| ${app.name} | ${ch.old} | ${ch.new} |`);
      }
      lines.push('');
    }

    if (ratingChanges.length > 0) {
      lines.push('### ⭐ Rating Changes');
      lines.push('');
      lines.push('| App | Old Rating | New Rating | Change |');
      lines.push('|-----|------------|------------|--------|');
      for (const app of ratingChanges) {
        const ch = app.changes.find(c => c.type === 'rating');
        const arrow = ch.delta > 0 ? '📈' : '📉';
        lines.push(`| ${app.name} | ${ch.old} | ${ch.new} | ${arrow} ${ch.delta > 0 ? '+' : ''}${ch.delta} |`);
      }
      lines.push('');
    }

    if (reviewChanges.length > 0) {
      lines.push('### 📝 Review Count Surges');
      lines.push('');
      lines.push('| App | Old Count | New Count | Change |');
      lines.push('|-----|-----------|-----------|--------|');
      for (const app of reviewChanges) {
        const ch = app.changes.find(c => c.type === 'reviewCount');
        lines.push(`| ${app.name} | ${ch.old} | ${ch.new} | +${ch.pctChange}% |`);
      }
      lines.push('');
    }
  }

  // No changes
  if (diff.summary.newApps === 0 && diff.summary.removedApps === 0 && diff.summary.appsWithChanges === 0) {
    lines.push('## 😴 No significant changes detected');
    lines.push('');
    lines.push('The Shopify App Store landscape remained stable between these two snapshots.');
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Shopify App Intel on ${new Date().toISOString()}*`);

  return lines.join('\n');
}

function main() {
  const diffPath = process.argv[2];
  if (!diffPath) {
    console.error('Usage: node newsletter.js <diff-file.json>');
    process.exit(1);
  }

  const diff = loadDiff(diffPath);
  const newsletter = generateNewsletter(diff);

  mkdirSync(join(import.meta.dirname, 'newsletters'), { recursive: true });
  const filename = `newsletter-${new Date().toISOString().split('T')[0]}.md`;
  const filepath = join(import.meta.dirname, 'newsletters', filename);
  writeFileSync(filepath, newsletter);

  console.log(`Newsletter saved: newsletters/${filename}`);
  console.log('\n--- Preview ---\n');
  console.log(newsletter);
}

main();
